config/routes.rb
GamesStore::Application.routes.draw do

  devise_for :users

  root :to => 'games#index'
  match '/show', to: 'games#show'
  match '/news',    to: 'news#show'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/link_download', to: 'static_pages#link_download'
  match '/games/search', to: 'games#search'
  
  match '/media/:dragonfly/:file_name', :to => Dragonfly[:images]

  resources :games do 
    resources :comments
    
    member do
      get 'rating'
    end
  end

  resources :payments

    namespace :admin do
      resources :games
      resources :users
      resources :categories
      resources :news
      resources :comments
      root :to => 'games#index'
    end

end

app/views/share/_choice_device.html.erb
<div class="modal hide" id="<%= gid %>" >
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Choice</h3>
  </div>
	
  <form action="<%= link_download_path %>">
  <div class="modal-body">
		<div class="row">
			<div class="span5">
    		<%= image_tag "/assets/iOS.jpg" %>
			</div>
		
			<div class="span5 pull-right">
				<%= image_tag "/assets/android.jpg" %>
			</div>
		</div>		
		
		<div class="row">
			<div class="span4" style="padding-left: 80px">
				<label class="radio">
					<input type="radio" name="device" id="optionsRadios2" value="iOS" checked> <b>iOS</b>
				</label>
			</div>
		
			<div class="span4" style="padding-left: 80px">
				<label class="radio">
					<input type="radio" name="device" id="optionsRadios2" value="Android"> <b>Android</b>
				</label>
			</div>
		</div>
		
		<input type="hidden" name="gameid" value="<%= gid %>">
		
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
		<button type="submit" class="btn">Download</button>
  </div>
	</form>
</div>

app/views/share/_comment.html.erb
<% if @comments.count > 4 %>
  <div class="scrollspy-example" >
    <%= render 'share/show_comment' %>
  </div>
<% else %>
  <%= render 'share/show_comment' %>
<% end %>

<% if current_user %> 
  <%= simple_form_for [@game, @comment] do |f| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :comment%>
    <%= f.text_area :content, size: "80x5"%>

    <div class="actions">
      <%= f.submit "Post"%>
    </div>
  <% end %>
<% end %>

app/views/share/_game_image_fields.html.erb
<div class="fields">
  <%#= f.input :image, as: :file %>
  <%#= f.input :_destroy, as: :hidden, input_html: { id: "image_#{f.object.id}" } %>
</div>

app/views/share/_related.html.erb
<div class="row">
  <% @game.game_related.each do |game| %>
    <div class="span2">
      <%= link_to image_tag(game.cover_image.thumb('100x100#').url,
      class: "element_popover", rel: "popover", title: game.name, :"data-content" => game.description),
      {:action => 'show', :controller => 'games', id: game} %>
      <p><b><%= game.name %></b></p>
      <% if @game.price == 0 %>
        <% if @game.link %>
          <%= link_to image_tag("download.png"), @game.link %>
        <% else %>
          <%= link_to image_tag("download.png"), "http://games.brothersoft.com/free-cat-games-download-s1.html"%>
        <% end %>
      <% else %>
        <% if signed_in? %>
          <%= link_to image_tag("buynow.png"), '/payments/new' %>
          <%# binding.pry %>
        <% else%>
          <%= link_to image_tag("buynow.png"), "#myModal", html_options = { :"data-toggle" => "modal"} %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/share/_screenshot.html.erb
<div id="id_of_gallery" class="gallery">
  <ul class="galleryBar">
		<% if @game_images.count > 0 %>
			<% @game_images.each do |game_image| %>
				<li><a href="<%= game_image.image.thumb('600x600').url %>" title="<%= game_image.image_name %>">
				<%= image_tag game_image.image.thumb('200x200').url %></a></li>
  		<% end %>
  	<% end %>
	</ul>
</div>

<script>
	$('#id_of_gallery').gallery({
		interval: 5500,
		height: '400px',
		width: '600px'
	});
</script>

app/views/share/_show_comment.html.erb
<table class="table table-striped">
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><b>
          <% if comment.user %>
            <%= comment.user.email %> 
          <% else %> (none)
          <% end %>:</b></br> <%= comment.content.gsub("\n","<br>").html_safe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/share/_signin.html.erb
<div class="modal hide" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Sign in</h3>
  </div>
  <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div class="modal-body">
    <div class="form-inputs">
    <%= f.input :email, :required => false, :autofocus => true %>
    <%= f.input :password, :required => false %>
    <%= f.input :remember_me, :as => :boolean if devise_mapping.rememberable? %>
		<%= link_to "Sign up", new_registration_path(resource_name) %><br />
	<%= link_to "Forgot your password?", new_password_path(resource_name) %>
    </div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <%= f.button :submit, "Sign in" %>
  </div>
  <% end %>
</div>