config/routes.rb
GamesStore::Application.routes.draw do

  devise_for :users

  root :to => 'games#index'
  match '/show', to: 'games#show'
  match '/news',    to: 'news#show'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/link_download', to: 'static_pages#link_download'
  match '/games/search', to: 'games#search'
  
  match '/media/:dragonfly/:file_name', :to => Dragonfly[:images]

  resources :games do 
    resources :comments
    
    member do
      get 'rating'
    end
  end

  resources :payments

    namespace :admin do
      resources :games
      resources :users
      resources :categories
      resources :news
      resources :comments
      root :to => 'games#index'
    end

end

app/models/game.rb
class Game
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::FullTextSearch
  
  field :name, type: String
  field :info, type: String

  field :banner_uid
  field :banner_name
  image_accessor :banner
  field :description, type: String # hien thi tren banner & javascrip

  field :cover_image_uid
  field :cover_image_name
  image_accessor :cover_image

  field :is_hot, type: Boolean, default: false
  field :price, type: Float, default: 0
  # field :rate_average, type: Float, default: 0
  field :link, type: String

  belongs_to :category
  validates :name, :category, presence: true
  delegate :name, to: :category, prefix: true, allow_nil: true
  has_many :comments
  has_many :game_images, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :game_images
  has_many :rates

  def self.names_ids
    all.map { |sc| ["#{sc.category_name} > #{sc.name}", sc.id] }.sort_by { |x| x.first }
  end

  def self.game_hot
    Game.find(:all, :conditions => { is_hot: true })
  end

  def game_related
    Game.where(category_id: self.category_id) - [self]
  end 
  
  def self.game_new
    Game.desc(:created_at)
  end
  
  def average_rating
    if rates.count > 0
      rates.map { |rate| rate.value }.inject{ |sum, el| sum + el }.to_f / rates.count
    else
      0
    end
  end
  
  def self.top_rated
    Game.all.sort {|a, b| b.average_rating <=> a.average_rating}
  end
  
  # Can phai chay lenh object.update_attributes()
  # Game.all.each do |g|
  #   g.update_attributes()
  # end
  fulltext_search_in :name, :ngram_width => 1
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::ApplicationController
  layout "admin"
 
  def index
    # binding.pry
    if params[:search_text].present?
      @games = Game.fulltext_search(params[:search_text], { :max_results => 100 })
    else
      @games = Game.all
    end
    
    @per_page = 5
    if params[:sort_by] == "average_rating"
      if params[:direction] == "asc"
        @games = @games.sort {|a, b| a.average_rating <=> b.average_rating}
      else
        @games = @games.sort {|a, b| b.average_rating <=> a.average_rating}
      end
    elsif params[:sort_by] == "name" || params[:sort_by] == "price"
      if params[:direction] == "asc"
        @games = @games.sort {|a, b| a[params[:sort_by].to_sym].to_s <=> b[params[:sort_by].to_sym].to_s}
      else
        @games = @games.sort {|a, b| b[params[:sort_by].to_sym].to_s <=> a[params[:sort_by].to_sym].to_s}
      end
    else
      @games = @games.sort {|a, b| a[:name].to_s <=> b[:name].to_s}
    end
    
    if @games.is_a? Array
      @games = Kaminari.paginate_array(@games).page(params[:page]).per(@per_page)
    else
      @games = @games.page(params[:page]).per(@per_page)
    end
  end

  def show
    @per_page = 5
    @game = Game.find(params[:id])
    @comments = @game.comments
    @game_images = @game.game_images
  end

  def new
    @game = Game.new
    5.times { @game.game_images.build }
  end

  def edit
    @game = Game.find(params[:id])
    (5 - @game.game_images.count).times { @game.game_images.build }
  end

  def create
    # binding.pry
    @game = Game.new(params[:game])

    if @game.save
      redirect_to [:admin, @game], notice: 'Game was successfully created.'
    else
      render action: "new" 
    end
  end

  def update
    @game = Game.find(params[:id])
    # binding.pry
    if @game.update_attributes(params[:game])
      redirect_to [:admin, @game], notice: 'Game was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.comments.delete_all
    @game.rates.delete_all
    @game.game_images.delete_all
    @game.destroy
    redirect_to admin_games_url
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  @actionpage = ""
  @cateid = ""
  
  def index
    @actionpage = "index"
    @games_hot_banner = Game.game_hot.limit(3)
    @per_page = 20
    
    if params[:category].nil?
      params[:category] = "all"
    end
    
    if params[:game] == "hot"
      if params[:category] != "all"
        @cateid = params[:category]
        @games = Game.where(:category_id => params[:category]).game_hot.page(params[:page]).per(@per_page)
      else
        @games = Game.game_hot.page(params[:page]).per(@per_page)
      end
    elsif params[:game] == "top"
      if params[:category] != "all"
        @cateid = params[:category]
        @games = Game.where(:category_id => params[:category]).top_rated
      else
        @games = Game.top_rated
      end
      @games = Kaminari.paginate_array(@games).page(params[:page]).per(@per_page)
    else
      if params[:category] != "all"
        @cateid = params[:category]
        @games = Game.where(:category_id => params[:category]).game_new.page(params[:page]).per(@per_page)
      else
        @games = Game.game_new.page(params[:page]).per(@per_page)
      end
    end
  end

  def search
    @actionpage = "index"
    @games_hot_banner = Game.game_hot.limit(3)
    @per_page = 5
    
    if params[:search_text].present?
      @games = Game.fulltext_search(params[:search_text], { :max_results => 100 })
      @games = Kaminari.paginate_array(@games).page(params[:page]).per(@per_page)
    else
      redirect_to root_path
    end
  end
  
  def show
    @actionpage = "show"
    @game = Game.find(params[:id])
    @comments = @game.comments
    @comment = current_user.comments.build if signed_in?
    @game_images = @game.game_images
  end

  def rating
    # binding.pry
    @game = Game.find(params[:id])
    if Rate.where(game_id: @game.id, user_id: current_user.id).count == 1
      @rate = Rate.where(game_id: @game.id, user_id: current_user.id).first
      @rate.update_attribute(:value, params[:value])
    else
      @rate = @game.rates.build
      @rate.value = params[:value]
      @rate.user_id = current_user.id
      @rate.save
    end
    redirect_to show_path(:id => @game.id)
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/_form.html.erb
<%= form_for [:admin, @game], :html => {:multipart => true, :class => "form-horizontal"} do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

    </div>
  <% end %>
	
	<div class="control-group">
		<label class="control-label">Name</label>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>
	
	<div class="control-group">
		<label class="control-label">Category</label>
		<div class="controls">
			<%= f.select :category, Category.all.collect {|c| [ c.name, c.id ] }, include_blank: false %>
		</div>
	</div>
	
	<div class="control-group">
		<label class="control-label">Info</label>
		<div class="controls">
			<%= f.text_area :info, size: "60x5"%>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">Description</label>
		<div class="controls">
			<%= f.text_area :description, size: "60x5"%>
		</div>
	</div>
	
	<div class="control-group">
		<label class="control-label">Avatar</label>
		<div class="controls">
			<% if controller.action_name == "new" %>
				<%= f.file_field :cover_image, required: true %>
			<% else %>
				<%= f.file_field :cover_image %>
				<div class="preview-img">
        	<%= image_tag @game.cover_image.thumb('50x50').url if !@game.cover_image_uid.nil? %>
      	</div>
			<% end %>
		</div>
	</div>

  <div class="control-group">
		<label class="control-label">Banner</label>
		<div class="controls">
			<% if controller.action_name == "new" %>
				<%= f.file_field :banner, required: true %>
			<% else %>
				<%= f.file_field :banner %>
				<div class="preview-img">
        	<%= image_tag @game.banner.thumb('100x100').url if !@game.banner_uid.nil? %>
      	</div>
			<% end %>
		</div>
	</div>
	
	<div class="control-group">
		<label class="control-label">Price</label>
		<div class="controls">
			<%= f.text_field :price %>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">Hot Game</label>
		<div class="controls">
			<%= f.check_box :is_hot %>
		</div>
	</div>
	
    <div class="control-group">
    <label class="control-label">Link download</label>
    <div class="controls">
      <%= f.text_field :link %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Image</label>
    <div class="controls">
      <%= f.fields_for :game_images do |game_image| %>
        <%= game_image.file_field :image %>
        </br>
        <%# if controller.action_name == "edit" %>
        <%#binding.pry%>
          <%#= image_tag game_image.image.thumb('100x100').url if game_image.image_uid %>
        <%# end %>
      <% end%>
    </div>  
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/games/_form_image.html.erb
<div class="fields">
  <%= f.input :image, as: :file%>
  <% binding.pry %>
  <%= f.input :_destroy, as: :hidden, input_html: { id: "image_#{f.object.id}" } %>
</div>

app/views/admin/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @game] %> |
<%= link_to 'Back', admin_games_path %>

app/views/admin/games/index.html.erb
<h1>Listing games</h1>


<%= link_to 'New Game', new_admin_game_path, class: "btn btn-primary" %>

<form class="pull-right">
  <input type="text" class="input-medium search-query" name="search_text">
  <button type="submit" class="btn">Search</button>
</form>

<table class="table table-striped" style="width:70% !important;">
  <thead>
    <tr>
      <th width="5%">#</th>
      <th width="10%">Avatar</th>
			<th width="19%"><%= sortable_link('average_rating', params[:direction], admin_games_path) %></th>
      <th width="20%"><%= sortable_link('name', params[:direction], admin_games_path) %></th>
      <th width="10%">Category</th>
      <th width="15%">Hot Game</th>
      <th width="10%"><%= sortable_link('price', params[:direction], admin_games_path) %></th>
      <th width="11%"></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each_with_index do |game, index| %>
      <tr>
      <td style="text-align: center"><%= index + 1 + (params[:page].present? ? (params[:page].to_i - 1)*@per_page : 0) %></td>
        <td><%= image_tag game.cover_image.thumb('100x100#').url if game.cover_image_uid %></td>
				<td><%= game.average_rating %></td>
        <td><%= game.name %></td>
        <td><%= game.category.name if game.category.present? %></td>
        <td><%= game.is_hot %></td>
        <td><%= game.price %> VND</td>
        <td>
          <%= link_to '<i class="icon-eye-open"></i>'.html_safe, [:admin, game] %>
          <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_game_path(game) %>
          <%= link_to '<i class="icon-remove-sign"></i>'.html_safe, [:admin, game], method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
</table>

<%= paginate @games %>

app/views/admin/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_games_path %>

app/views/admin/games/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", admin_root_path %></li> <span class="divider">/</span>
  <li><%= link_to "Games", admin_games_path %></li> <span class="divider">/</span>
  <li class="active">Show</li>
</ul>

<h1>Show Game</h1><br/>

<div class="tabbable" style="margin-bottom: 18px;">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#information" data-toggle="tab">Information</a></li>
    <li class=""><a href="#comments" data-toggle="tab">Comments</a></li>
  </ul>
  
  <div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
    <div class="tab-pane active" id="information">
      <p><%= image_tag @game.cover_image.thumb('100x100#').url %></p>
      <p><b>Name:</b><%= @game.name %></p>
      <p><b>Category:</b><%= @game.category.name if @game.category.present? %></p>
      <p><b>Information:</b><%= @game.info.gsub("\n","<br>").html_safe %></p>
      <p><b>Hot Game:</b><%= @game.is_hot %></p>
      <p><b>Price:</b><%= @game.price %></p>
			<p><b>Average rating:</b><%= @game.average_rating %></p>
      <p>
        <b>Image:</b></br>
          <% if @game_images.count > 0 %>
            <% @game_images.each do |game_image| %>
							<!-- <div class="preview-img"> -->
              <%= image_tag game_image.image.thumb('200x200').url %>
						  <!-- </div> -->
            <% end %>
          <% end %>
      </p>

    </div>

    <div class="tab-pane" id="comments" style=" height: 210px; overflow-y: scroll;">
      <!-- <div class="scrollspy-example"> -->
        <table class="table table-striped">
          <% @comments.each_with_index do |comment, index| %>
            <tr>
              <td width="5%" style="text-align: center"><%= index+1 %></td>
              <td width="20%"><%= comment.user.email %></td>
              <td><%= comment.content.gsub("\n","<br>").html_safe %></td>
            </tr>
          <% end %>
        </table>
      <!-- </div> -->
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_admin_game_path(@game) %> |
<%= link_to 'Back', admin_games_path %>