config/routes.rb
GamesStore::Application.routes.draw do

  devise_for :users

  root :to => 'games#index'
  match '/show', to: 'games#show'
  match '/news',    to: 'news#show'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/link_download', to: 'static_pages#link_download'
  match '/games/search', to: 'games#search'
  
  match '/media/:dragonfly/:file_name', :to => Dragonfly[:images]

  resources :games do 
    resources :comments
    
    member do
      get 'rating'
    end
  end

  resources :payments

    namespace :admin do
      resources :games
      resources :users
      resources :categories
      resources :news
      resources :comments
      root :to => 'games#index'
    end

end

app/models/category.rb
class Category
  include Mongoid::Document
  
  field :name, type: String

  has_many :games

  validates_presence_of :name

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  layout "admin"
  
  def index
    @categories  = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to [:admin, @category], notice: 'category was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to [:admin, @category], notice: 'category was successfully updated.'
    else
      render action: "edit"
    end
  end

 def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to admin_categories_url
 end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], :html => {:multipart => true} do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @category] %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Listing categories</h1>

<table class="table table-striped" style="width:70% !important;">
  <thead>
    <tr>
      <th width="20%">Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>

        <td><%= link_to '<i class="icon-eye-open"></i>'.html_safe, [:admin, category] %></td>
        <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_category_path(category) %></td>
        <td><%= link_to '<i class="icon-remove-sign"></i>'.html_safe, [:admin, category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br />

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="name">
    <p><b><%= @category.name %></b></p>
  </div>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>