config/routes.rb
GamesStore::Application.routes.draw do

  devise_for :users

  root :to => 'games#index'
  match '/show', to: 'games#show'
  match '/news',    to: 'news#show'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/link_download', to: 'static_pages#link_download'
  match '/games/search', to: 'games#search'
  
  match '/media/:dragonfly/:file_name', :to => Dragonfly[:images]

  resources :games do 
    resources :comments
    
    member do
      get 'rating'
    end
  end

  resources :payments

    namespace :admin do
      resources :games
      resources :users
      resources :categories
      resources :news
      resources :comments
      root :to => 'games#index'
    end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::FullTextSearch
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  has_many :comments

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  def admin?
    email == 'admin@ymail.com'
  end
  
  fulltext_search_in :email, :ngram_width => 1
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  layout "admin"
  def index
    if params[:search_text].present?
      @users = User.fulltext_search(params[:search_text], { :max_results => 100 })
    else
      @users = User.all
    end
    
    @per_page = 5
    if params[:sort_by].present?
      if params[:direction] == "asc"
        @users = @users.sort {|a, b| a[params[:sort_by].to_sym].to_s <=> b[params[:sort_by].to_sym].to_s}
      else
        @users = @users.sort {|a, b| b[params[:sort_by].to_sym].to_s <=> a[params[:sort_by].to_sym].to_s}
      end
    else
      @users = @users.sort {|a, b| a[:email].to_s <=> b[:email].to_s}
    end
    
    if @users.is_a? Array
      @users = Kaminari.paginate_array(@users).page(params[:page]).per(@per_page)
    else
      @users = @users.page(params[:page]).per(@per_page)
    end

  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_without_password(params[:user])
      redirect_to [:admin, @user], notice: 'User was successfully updated'
    else
      render action: "edit"
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to [:admin, @user], notice: "User was successfully created."
    else
      render action: "new"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user], :html => {:class => "form-horizontal"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.input :email, required: true %>
  </div>
  <div class="control-group">
  <% if controller.action_name == "new" %>
    <%= f.input :password, required: true %>
  <% else %>
    <%= f.input :password %>
  <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<ul class="breadcrumb">
<li>
  <a href="<%= admin_users_path %>">Home</a> <span class="divider">/</span>
</li>
<li class="active">Edit</li>
</ul>

<h1>Edit user</h1><br/>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", admin_root_path %></li> <span class="divider">/</span>
  <li class="active">Users</li>
</ul>

<h1>Listing users</h1>

<%= link_to 'New user', new_admin_user_path, class: "btn btn-primary" %>

<form class="pull-right">
  <input type="text" class="input-medium search-query" name="search_text">
  <button type="submit" class="btn">Search</button>
</form>

<table class="table table-striped" style="width:70% !important;">
  <thead>
    <tr>
      <th>#</th>
      <th><%= sortable_link('email', params[:direction], admin_users_path) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index + 1 + (params[:page].present? ? (params[:page].to_i - 1)*@per_page : 0) %></td>
        <td><%= user.email %></td>

        <td><%= link_to '<i class="icon-eye-open"></i>'.html_safe, [:admin, user] %></td>
        <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_user_path(user) %></td>
        <td><%= link_to '<i class="icon-remove-sign"></i>'.html_safe, [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<%= paginate @users%>

app/views/admin/users/new.html.erb
<ul class="breadcrumb">
<li>
  <a href="<%= admin_users_path %>">Home</a> <span class="divider">/</span>
</li>
<li class="active">New</li>
</ul>

<h1>New user</h1><br/>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", admin_root_path %></li> <span class="divider">/</span>
  <li><%= link_to "Users", admin_users_path %></li> <span class="divider">/</span>
  <li class="active">Show</li>
</ul>

<h1>Show User</h1><br/>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>